### ISSUE TITLE
Dependency Install Failed

### ISSUE THREAD

**Issue by Waffle1434** [xy-gao/splatviz-blender#4]
Windows 10
Blender 4.2.1
CUDA 11.8
Console log: https://pastebin.com/R3wanZJk

Excerpts:
```Py
Building wheel for diff_gauss (pyproject.toml) did not run successfully
RuntimeError: Error compiling objects for extension
ERROR: Failed building wheel for diff_gauss

Building wheel for simple_knn (pyproject.toml) did not run successfully
RuntimeError: Error compiling objects for extension
ERROR: Failed building wheel for simple_knn

ERROR: Could not build wheels for diff_gauss, simple_knn, which is required to install pyproject.toml-based projects
```

**Comment by Arctecdev** [comment]
Cant solve this too..

Trying hard..

**Comment by xy-gao** [comment]
`   C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\crt/host_config.h(153): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) are supported! `

CUDA 11.8 not working with latest Visual Studio.
I fixed the code which should work on CUDA 12.6 (latest) and Visual Studio 17.11.5 (latest) now.

**Comment by BAPTISTE-Ryan** [comment]
same error with config : 

Win11

arch : AMD 

NVIDIA (R) Cuda compiler driver Cuda compilation tools, release 12.6, V12.6.77 Build cuda_12.6.r12.6/compiler.34841621_0

 Microsoft (R) C/C++ version 19.29.30158 x64
